# Generated by Django 5.2.2 on 2025-06-10 23:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cards", "0001_initial"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="cardprinting",
            unique_together=set(),
        ),
        migrations.AddField(
            model_name="cardprinting",
            name="art_variation",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterUniqueTogether(
            name="cardprinting",
            unique_together={
                ("card", "set", "foiling", "rarity", "edition", "art_variation")
            },
        ),
    ]
