# Generated by Django 5.2.2 on 2025-06-09 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cards", "0002_usercard"),
    ]

    operations = [
        migrations.CreateModel(
            name="CardSubType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name="CardType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name="Keyword",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.RemoveField(
            model_name="card",
            name="type",
        ),
        migrations.AddField(
            model_name="card",
            name="subtypes",
            field=models.ManyToManyField(blank=True, to="cards.cardsubtype"),
        ),
        migrations.AddField(
            model_name="card",
            name="tycard_types",
            field=models.ManyToManyField(blank=True, to="cards.cardtype"),
        ),
        migrations.AddField(
            model_name="card",
            name="keywords",
            field=models.ManyToManyField(blank=True, to="cards.keyword"),
        ),
    ]
