# Generated by Django 5.2.2 on 2025-06-10 23:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("cards", "0002_alter_cardprinting_unique_together_and_more"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="cardprinting",
            unique_together={
                (
                    "card",
                    "set",
                    "foiling",
                    "rarity",
                    "edition",
                    "art_variation",
                    "card_number",
                )
            },
        ),
    ]
