# Generated by Django 5.2.2 on 2025-06-09 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cards", "0003_cardsubtype_cardtype_keyword_remove_card_type_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="card",
            old_name="tycard_types",
            new_name="card_type",
        ),
        migrations.AddField(
            model_name="card",
            name="foil",
            field=models.CharField(
                choices=[
                    ("NF", "No Foil"),
                    ("RF", "Rainbow Foil"),
                    ("CF", "Cold Foil"),
                ],
                default="NF",
                max_length=2,
            ),
        ),
        migrations.AlterField(
            model_name="card",
            name="pitch",
            field=models.IntegerField(
                blank=True,
                choices=[(1, "Blue (1)"), (2, "Yellow (2)"), (3, "Red (3)")],
                null=True,
            ),
        ),
    ]
