# Generated by Django 5.2.2 on 2025-06-09 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cards", "0004_rename_tycard_types_card_card_type_card_foil_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="CardTypes",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
            ],
        ),
        migrations.RemoveField(
            model_name="card",
            name="card_type",
        ),
        migrations.RemoveField(
            model_name="card",
            name="subtypes",
        ),
        migrations.AddField(
            model_name="card",
            name="types",
            field=models.ManyToManyField(related_name="cards", to="cards.cardtype"),
        ),
    ]
