# Generated by Django 5.2.2 on 2025-06-17 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cards", "0006_usercardprintings_delete_usercard"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="set",
            name="code",
        ),
        migrations.AddField(
            model_name="set",
            name="card_gallery",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="set",
            name="collectors_center",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="set",
            name="edition",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="set",
            name="end_card_id",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="set",
            name="out_of_print",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="set",
            name="product_page",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="set",
            name="set_id",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="set",
            name="set_logo",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="set",
            name="start_card_id",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="set",
            name="unique_id",
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name="set",
            name="name",
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name="set",
            name="release_date",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
