# Generated by Django 5.2.2 on 2025-06-17 21:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cards", "0007_remove_set_code_set_card_gallery_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="set",
            name="card_gallery",
        ),
        migrations.RemoveField(
            model_name="set",
            name="collectors_center",
        ),
        migrations.RemoveField(
            model_name="set",
            name="edition",
        ),
        migrations.RemoveField(
            model_name="set",
            name="end_card_id",
        ),
        migrations.RemoveField(
            model_name="set",
            name="out_of_print",
        ),
        migrations.RemoveField(
            model_name="set",
            name="product_page",
        ),
        migrations.RemoveField(
            model_name="set",
            name="release_date",
        ),
        migrations.RemoveField(
            model_name="set",
            name="set_logo",
        ),
        migrations.RemoveField(
            model_name="set",
            name="start_card_id",
        ),
        migrations.AlterField(
            model_name="set",
            name="set_id",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.CreateModel(
            name="SetPrinting",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("unique_id", models.CharField(max_length=255)),
                ("edition", models.CharField(max_length=2)),
                ("start_card_id", models.CharField(max_length=50)),
                ("end_card_id", models.CharField(max_length=50)),
                ("initial_release_date", models.DateField()),
                ("out_of_print", models.BooleanField(default=False)),
                ("card_database", models.URLField()),
                ("product_page", models.URLField()),
                ("collectors_center", models.URLField(blank=True, null=True)),
                ("card_gallery", models.URLField(blank=True, null=True)),
                ("set_logo", models.URLField(blank=True, null=True)),
                ("release_notes", models.URLField(blank=True, null=True)),
                (
                    "set",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="printings",
                        to="cards.set",
                    ),
                ),
            ],
        ),
    ]
