# Generated by Django 5.2.2 on 2025-06-17 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cards", "0008_remove_set_card_gallery_remove_set_collectors_center_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="setprinting",
            name="card_database",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="setprinting",
            name="product_page",
            field=models.URLField(blank=True, null=True),
        ),
    ]
