# Generated by Django 5.2.2 on 2025-06-17 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cards", "0009_alter_setprinting_card_database_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="setprinting",
            name="initial_release_date",
            field=models.DateField(blank=True, null=True),
        ),
    ]
