# Generated by Django 5.2.2 on 2025-06-19 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cards", "0010_alter_setprinting_initial_release_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="rarity",
            name="description",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
