# Generated by Django 5.2.2 on 2025-06-19 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cards", "0011_rarity_description"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cardprinting",
            name="foiling",
            field=models.CharField(
                blank=True,
                choices=[
                    ("S", "Standard"),
                    ("R", "Rainbow Foil"),
                    ("C", "Cold Foil"),
                    ("G", "Gold Foil"),
                ],
                max_length=10,
                null=True,
            ),
        ),
    ]
