# Generated by Django 5.2.2 on 2025-06-19 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cards", "0012_alter_cardprinting_foiling"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cardprinting",
            name="edition",
            field=models.CharField(
                blank=True,
                choices=[
                    ("A", "Alpha"),
                    ("F", "First"),
                    ("U", "Unlimited"),
                    ("N", "No specified edition"),
                ],
                max_length=10,
                null=True,
            ),
        ),
    ]
