# Generated by Django 5.2.2 on 2025-06-19 20:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cards", "0013_alter_cardprinting_edition"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="cardprinting",
            name="set",
        ),
        migrations.AddField(
            model_name="cardprinting",
            name="set_printing",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="cards.setprinting",
            ),
        ),
    ]
